eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8081
spring:
  application:
    name: WelcomeApi
  boot:
    admin:
      client:
        url: http://localhost:9090/



  config:
    import: optional:configserver:http://localhost:8888
    
  cloud:
    config:
      enabled: false



